import PieChartCard from "../components/PieChartCard";
import {
  Card,
  Grid,
  CardHeader,
  Avatar,
  IconButton,
  Typography,
} from "@mui/material";
import StatisticsShowNumberCard from "../components/StatisticsShowNumberCard";
import PersonIcon from "@mui/icons-material/Person";
import MonetizationOnTwoToneIcon from "@mui/icons-material/MonetizationOnTwoTone";
import FastfoodTwoToneIcon from "@mui/icons-material/FastfoodTwoTone";
import {
  ChartContainer,
  LineChart,
  LinePlot,
  SparkLineChart,
  lineElementClasses,
  markElementClasses,
} from "@mui/x-charts";
export default function GeneralAnalytics() {
  return (
    <Grid
      container
      sx={{ padding: 5, backgroundColor: "gray", paddingTop: 30 }}
      spacing={2}
    >
      <Grid container spacing={2} item sm={12}>
        <Grid item sm={4}>
          <StatisticsShowNumberCard
            headerTitle="Number of users"
            headerSubTitle="the number of users using the app"
            iconComponent={<PersonIcon sx={{ fontSize: "5rem" }} />}
          ></StatisticsShowNumberCard>
        </Grid>
        <Grid item sm={4}>
          <StatisticsShowNumberCard
            headerTitle="Number of users"
            headerSubTitle="the number of users using the app"
            iconComponent={
              <MonetizationOnTwoToneIcon
                sx={{
                  fontSize: "5rem",
                  color: "green",
                }}
              />
            }
          ></StatisticsShowNumberCard>
        </Grid>
        <Grid item sm={4}>
          <StatisticsShowNumberCard
            headerTitle="Number of meals"
            headerSubTitle="the number of meals generated by users"
            iconComponent={
              <FastfoodTwoToneIcon
                sx={{
                  fontSize: "5rem",
                  color: "purple",
                }}
              />
            }
          ></StatisticsShowNumberCard>
        </Grid>
      </Grid>
      <Grid container spacing={2} sm={8} item>
        <Grid item sm={6}>
          <PieChartCard
            headerTitle="Allergic-to percentage"
            headerSubTitle="see the percentage of the people that have allergic"
          />
        </Grid>
        <Grid item sm={6}>
          <PieChartCard
            headerTitle="Religion distribution"
            headerSubTitle="see the percentage of each religion"
          />
        </Grid>
        <Grid item sm={12}>
          <Card
            sx={{
              minHeight: 400,
              display: "flex",
              alignItems: "center",
              flexDirection: "column",
            }}
          >
            <CardHeader title="Number of users signed up by year" />
            <LineChart
              xAxis={[{ data: [1, 2, 3, 5, 8, 10] }]}
              yAxis={[{ label: "Number of users" }]}
              series={[
                {
                  data: [2, 5.5, 2, 8.5, 1.5, 5],
                },
              ]}
              height={400}
            />
          </Card>
        </Grid>
      </Grid>
      <Grid item container sm={4}>
        <Grid
          item
          sm={12}
          component={Card}
          sx={{ width: "100%", height: "100%" }}
        >
          <Card sx={{ margin: 2 }}>
            <CardHeader title="Purchases transactions" subheader="" />
            <Card
              sx={{
                margin: 2,
                background: "#ece5f4",
              }}
            >
              <LineChart
                xAxis={[
                  {
                    data: [1, 2, 3, 5, 8, 10],
                  },
                ]}
                series={[
                  {
                    data: [2, 5.5, 2, 8.5, 1.5, 5],
                    area: true,
                  },
                ]}
                leftAxis={null}
                bottomAxis={null}
                height={300}
              />
            </Card>
          </Card>
          <CardHeader title="Transactions" />
          <Grid
            item
            sx={{
              height: "300px",
              overflow: "scroll",
              margin: 2,
              background: "#ece5f4",
            }}
          >
            {[1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9].map((itme) => (
              <Card>
                <CardHeader title="Purchases transactions" subheader="" />
              </Card>
            ))}
          </Grid>
        </Grid>
      </Grid>
    </Grid>
  );
}
